# Generated by Django 3.2.9 on 2022-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('O+', 'O POSITIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
    ]
