# Generated by Django 3.2.9 on 2022-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0002_alter_bloodgroup_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
