# Generated by Django 3.2.9 on 2022-08-09 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0003_auto_20220809_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cncapp.gender'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
    ]
