# Generated by Django 3.2.9 on 2022-08-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0004_auto_20220809_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
