# Generated by Django 3.2.9 on 2022-08-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0005_auto_20220809_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('AB+', 'AB POSITIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
    ]
