# Generated by Django 3.2.9 on 2022-08-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0007_auto_20220810_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE')], default='B+', max_length=15),
        ),
    ]
