# Generated by Django 3.2.9 on 2022-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0009_auto_20220810_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
    ]
