# Generated by Django 3.2.9 on 2022-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0012_alter_bloodgroup_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('A+', 'A POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='contact_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pincode',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
