# Generated by Django 3.2.9 on 2022-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0014_auto_20220812_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O+', 'O POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
    ]
