# Generated by Django 3.2.9 on 2022-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0015_alter_bloodgroup_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
    ]
