# Generated by Django 3.2.9 on 2022-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0017_auto_20220813_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aadhaarno',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
