# Generated by Django 3.2.9 on 2022-08-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0018_auto_20220813_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
