# Generated by Django 3.2.9 on 2022-08-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0019_auto_20220813_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='medicineimage',
            field=models.ImageField(blank=True, upload_to='medicine_pics'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
    ]
