# Generated by Django 4.0.6 on 2022-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0020_auto_20220813_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='desc',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='areacode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhaarno',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='contact_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
