# Generated by Django 4.0.6 on 2022-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0021_inventory_desc_alter_ambulance_areacode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
    ]
