# Generated by Django 4.0.6 on 2022-08-14 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0022_alter_bloodgroup_bloodgroup_alter_gender_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='desc',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctorimage',
            field=models.ImageField(blank=True, upload_to='doctor_pics'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='medavailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cncapp.inventory'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
    ]
