# Generated by Django 4.0.6 on 2022-08-14 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0024_pharmacist_end_time_pharmacist_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.AddField(
            model_name='doctor',
            name='ratings',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('A-', 'A NEGATIVE'), ('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ratings',
            field=models.FloatField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
