# Generated by Django 4.0.6 on 2022-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0025_remove_doctor_rating_doctor_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
