# Generated by Django 4.0.6 on 2022-08-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0026_alter_bloodgroup_bloodgroup_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
    ]
