# Generated by Django 4.0.6 on 2022-08-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0027_alter_bloodgroup_bloodgroup_alter_gender_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='inventory',
        ),
        migrations.AddField(
            model_name='doctorappoinment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contactno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ratings',
            field=models.FloatField(null=True, unique=True),
        ),
    ]
