# Generated by Django 4.0.6 on 2022-08-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0028_remove_pharmacist_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
