# Generated by Django 4.0.6 on 2022-08-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0029_alter_bloodgroup_bloodgroup_alter_gender_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pharma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cncapp.pharmacist'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
    ]
