# Generated by Django 4.0.6 on 2022-08-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0030_inventory_pharma_alter_bloodgroup_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='gender',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
