# Generated by Django 4.0.6 on 2022-08-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0031_remove_inventory_user_alter_bloodgroup_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappoinment',
            name='reschedule',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='Bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE')], default='B+', max_length=15),
        ),
    ]
