# Generated by Django 4.0.6 on 2022-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0032_doctorappoinment_reschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ambulance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pharmacist',
        ),
        migrations.AddField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Hospital', 'is_Hospital'), ('Patient', 'is_Patient'), ('Pharmacist', 'is_Pharmacist'), ('Ambulance', 'is_Ambulance'), ('Doctor', 'is_Doctor'), ('Driver', 'is-Driver')], default='Doctor', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
