# Generated by Django 4.0.6 on 2022-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0033_remove_user_is_ambulance_remove_user_is_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contactno',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Pharmacist', 'is_Pharmacist'), ('Doctor', 'is_Doctor'), ('Driver', 'is-Driver'), ('Patient', 'is_Patient'), ('Ambulance', 'is_Ambulance'), ('Hospital', 'is_Hospital')], default='Doctor', max_length=50),
        ),
    ]
