# Generated by Django 4.0.6 on 2022-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0034_remove_user_contactno_user_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('B-', 'B NEGATIVE'), ('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('O-', 'O NEGATIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Doctor', 'is_Doctor'), ('Ambulance', 'is_Ambulance'), ('Driver', 'is-Driver'), ('Patient', 'is_Patient'), ('Hospital', 'is_Hospital'), ('Pharmacist', 'is_Pharmacist')], default='Doctor', max_length=50),
        ),
    ]
