# Generated by Django 4.0.6 on 2022-08-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0036_alter_patient_bloodgroup_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Ambulance', 'is_Ambulance'), ('Patient', 'is_Patient'), ('Doctor', 'is_Doctor'), ('Hospital', 'is_Hospital'), ('Pharmacist', 'is_Pharmacist'), ('Driver', 'is-Driver')], default='Doctor', max_length=50),
        ),
    ]
