# Generated by Django 4.0.6 on 2022-08-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0037_user_bloodgroup_user_gender_alter_doctor_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Driver', 'is-Driver'), ('Patient', 'is_Patient'), ('Pharmacist', 'is_Pharmacist'), ('Doctor', 'is_Doctor'), ('Hospital', 'is_Hospital'), ('Ambulance', 'is_Ambulance')], default='Doctor', max_length=50),
        ),
    ]
