# Generated by Django 4.0.6 on 2022-08-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0039_alter_patient_bloodgroup_alter_user_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Hospital', 'is_Hospital'), ('Ambulance', 'is_Ambulance'), ('Patient', 'is_Patient'), ('Doctor', 'is_Doctor'), ('Driver', 'is-Driver'), ('Pharmacist', 'is_Pharmacist')], default='Doctor', max_length=50),
        ),
    ]
