# Generated by Django 4.0.6 on 2022-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0040_alter_patient_bloodgroup_alter_user_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Driver', 'is-Driver'), ('Ambulance', 'is_Ambulance'), ('Patient', 'is_Patient'), ('Doctor', 'is_Doctor'), ('Pharmacist', 'is_Pharmacist'), ('Hospital', 'is_Hospital')], default='Doctor', max_length=50),
        ),
    ]
