# Generated by Django 4.0.6 on 2022-08-16 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0041_alter_doctor_gender_alter_patient_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^(\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?$', 'The phone number provided is invalid')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Patient', 'is_Patient'), ('Ambulance', 'is_Ambulance'), ('Hospital', 'is_Hospital'), ('Pharmacist', 'is_Pharmacist'), ('Doctor', 'is_Doctor'), ('Driver', 'is-Driver')], default='Doctor', max_length=50),
        ),
    ]
