# Generated by Django 3.2.15 on 2022-08-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0042_alter_doctor_gender_alter_patient_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Driver', 'is-Driver'), ('Pharmacist', 'is_Pharmacist'), ('Patient', 'is_Patient'), ('Hospital', 'is_Hospital'), ('Doctor', 'is_Doctor'), ('Ambulance', 'is_Ambulance')], default='Doctor', max_length=50),
        ),
    ]
