# Generated by Django 3.2.15 on 2022-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0044_auto_20220816_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Patient', 'is_Patient'), ('Ambulance', 'is_Ambulance'), ('Doctor', 'is_Doctor'), ('Hospital', 'is_Hospital'), ('Driver', 'is-Driver'), ('Pharmacist', 'is_Pharmacist')], default='Doctor', max_length=50),
        ),
    ]
