# Generated by Django 3.2.15 on 2022-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0046_auto_20220816_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Pharmacist', 'is_Pharmacist'), ('Patient', 'is_Patient'), ('Ambulance', 'is_Ambulance'), ('Driver', 'is-Driver'), ('Hospital', 'is_Hospital'), ('Doctor', 'is_Doctor')], default='Doctor', max_length=50),
        ),
    ]
