# Generated by Django 3.2.15 on 2022-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0049_auto_20220816_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Ambulance', 'is_Ambulance'), ('Hospital', 'is_Hospital'), ('Pharmacist', 'is_Pharmacist'), ('Doctor', 'is_Doctor'), ('Patient', 'is_Patient'), ('Driver', 'is-Driver')], default='Doctor', max_length=50),
        ),
    ]
