# Generated by Django 3.2.15 on 2022-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0050_auto_20220816_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Ambulance', 'is_Ambulance'), ('Pharmacist', 'is_Pharmacist'), ('Hospital', 'is_Hospital'), ('Doctor', 'is_Doctor'), ('Patient', 'is_Patient'), ('Driver', 'is-Driver')], default='Doctor', max_length=50),
        ),
    ]
