# Generated by Django 3.2.15 on 2022-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0053_auto_20220816_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappoinment',
            name='reschedule',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B+', 'B POSITIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B+', 'B POSITIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Patient', 'is_Patient'), ('Doctor', 'is_Doctor'), ('Pharmacist', 'is_Pharmacist'), ('Driver', 'is-Driver'), ('Hospital', 'is_Hospital'), ('Ambulance', 'is_Ambulance')], default='Doctor', max_length=50),
        ),
    ]
