# Generated by Django 3.2.15 on 2022-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0054_auto_20220816_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ratings',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Pharmacist', 'is_Pharmacist'), ('Doctor', 'is_Doctor'), ('Hospital', 'is_Hospital'), ('Patient', 'is_Patient'), ('Driver', 'is-Driver'), ('Ambulance', 'is_Ambulance')], default='Doctor', max_length=50),
        ),
    ]
