# Generated by Django 3.2.15 on 2022-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0055_auto_20220816_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('B+', 'B POSITIVE'), ('AB+', 'AB POSITIVE'), ('O-', 'O NEGATIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Doctor', 'is_Doctor'), ('Driver', 'is-Driver'), ('Hospital', 'is_Hospital'), ('Patient', 'is_Patient'), ('Ambulance', 'is_Ambulance'), ('Pharmacist', 'is_Pharmacist')], default='Doctor', max_length=50),
        ),
    ]
