# Generated by Django 3.2.9 on 2022-08-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0057_auto_20220817_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Ambulance', 'is_Ambulance'), ('Patient', 'is_Patient'), ('Pharmacist', 'is_Pharmacist'), ('Doctor', 'is_Doctor'), ('Driver', 'is-Driver'), ('Hospital', 'is_Hospital')], default='Doctor', max_length=50),
        ),
    ]
