# Generated by Django 3.2.15 on 2022-08-20 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0058_auto_20220817_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalappointment',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='hospitalappointment',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='hospitalappointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_no',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contactno',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ratings',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhaarno',
            field=models.CharField(default=0, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='contact_no',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aadhaarno',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contactno',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='contact_no',
            field=models.CharField(default=0, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('1', 'Doctor'), ('2', 'Patient'), ('4', 'Pharmacist'), ('3', 'Hospital'), ('5', 'Ambulance')], default='Doctor', max_length=50),
        ),
        migrations.DeleteModel(
            name='DoctorAppoinment',
        ),
        migrations.DeleteModel(
            name='HospitalAppointment',
        ),
    ]
