# Generated by Django 3.2.15 on 2022-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0059_auto_20220820_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact_no',
            field=models.CharField(default=0, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A-', 'A NEGATIVE'), ('O-', 'O NEGATIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='start_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('A-', 'A NEGATIVE'), ('O-', 'O NEGATIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('B+', 'B POSITIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('4', 'Pharmacist'), ('1', 'Doctor'), ('3', 'Hospital'), ('5', 'Ambulance'), ('2', 'Patient')], default='Doctor', max_length=50),
        ),
    ]
