# Generated by Django 3.2.15 on 2022-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0060_auto_20220820_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('O-', 'O NEGATIVE'), ('B-', 'B NEGATIVE'), ('A+', 'A POSITIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Ambulance', 'Ambulance'), ('Hospital', 'Hospital'), ('Patient', 'Patient'), ('Pharmacist', 'Pharmacist'), ('Doctor', 'Doctor')], default='Doctor', max_length=50),
        ),
    ]
