# Generated by Django 3.2.15 on 2022-08-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0061_auto_20220820_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('A-', 'A NEGATIVE'), ('AB-', 'AB NEGATIVE'), ('B-', 'B NEGATIVE'), ('A+', 'A POSITIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('O+', 'O POSITIVE')], default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Ambulance', 'Ambulance'), ('Hospital', 'Hospital'), ('Pharmacist', 'Pharmacist'), ('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Doctor', max_length=50),
        ),
    ]
