# Generated by Django 3.2.15 on 2022-08-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0063_auto_20220821_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='B+', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('B+', 'B POSITIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE'), ('A+', 'A POSITIVE'), ('B-', 'B NEGATIVE')], default='B+', max_length=15),
        ),
    ]
