# Generated by Django 3.2.15 on 2022-08-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0064_auto_20220821_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB-', 'AB NEGATIVE'), ('O-', 'O NEGATIVE'), ('AB+', 'AB POSITIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('O+', 'O POSITIVE'), ('A-', 'A NEGATIVE'), ('A+', 'A POSITIVE')], default='B+', max_length=15),
        ),
        migrations.CreateModel(
            name='Datashare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=0, max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('contactno', models.CharField(default=0, max_length=10)),
                ('disease', models.TextField(max_length=300)),
                ('aadhaarno', models.CharField(default=0, max_length=12)),
                ('emergency', models.TextField(max_length=400, null=True)),
                ('gender', models.CharField(default='M', max_length=10)),
                ('bloodgroup', models.CharField(default='B+', max_length=15)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cncapp.hospital')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cncapp.patient')),
            ],
        ),
    ]
