# Generated by Django 3.2.15 on 2022-08-21 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0065_auto_20220821_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datashare',
            old_name='doctor_name',
            new_name='hospital',
        ),
        migrations.RemoveField(
            model_name='datashare',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='datashare',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datashare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('AB+', 'AB POSITIVE'), ('A+', 'A POSITIVE'), ('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
    ]
