# Generated by Django 3.2.15 on 2022-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0069_alter_user_bloodgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='driver',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='Ambulanceimage',
            field=models.ImageField(blank=True, upload_to='ambulance_pics'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='company',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='contact_no',
            field=models.CharField(default=0, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='desc',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='ratings',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(choices=[('B-', 'B NEGATIVE'), ('O-', 'O NEGATIVE'), ('B+', 'B POSITIVE'), ('A-', 'A NEGATIVE'), ('A+', 'A POSITIVE'), ('AB+', 'AB POSITIVE'), ('O+', 'O POSITIVE'), ('AB-', 'AB NEGATIVE')], default='B+', max_length=15),
        ),
    ]
