# Generated by Django 3.2.15 on 2022-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0074_auto_20220825_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(max_length=30),
        ),
    ]
