# Generated by Django 3.2.15 on 2022-08-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0075_auto_20220825_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
    ]
