# Generated by Django 3.2.15 on 2022-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0076_auto_20220825_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
