# Generated by Django 3.2.15 on 2022-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0077_auto_20220825_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='areacode',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='vehicleno',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='ratings',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='city',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='desc',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default=0, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=20),
        ),
    ]
