# Generated by Django 3.2.15 on 2022-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0078_auto_20220828_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorimage',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_pics'),
        ),
    ]
