# Generated by Django 3.2.15 on 2022-08-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0079_alter_doctor_doctorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
