# Generated by Django 3.2.15 on 2022-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0080_doctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitalimage',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_pics'),
        ),
    ]
