# Generated by Django 3.2.15 on 2022-08-29 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0082_alter_ambulance_ambulanceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocDatashare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=0, max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('contactno', models.CharField(default=0, max_length=13)),
                ('disease', models.TextField(max_length=300)),
                ('aadhaarno', models.CharField(default=0, max_length=12)),
                ('emergency', models.TextField(max_length=400, null=True)),
                ('gender', models.CharField(default='M', max_length=10)),
                ('bloodgroup', models.CharField(default='B+', max_length=15)),
                ('accept', models.BooleanField(default=False)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cncapp.ambulance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
