# Generated by Django 3.2.15 on 2022-08-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0083_docdatashare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdatashare',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cncapp.doctor'),
        ),
    ]
