# Generated by Django 3.2.15 on 2022-09-03 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0084_alter_docdatashare_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('booking_amount', models.CharField(max_length=25)),
                ('booking_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(default=0)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cncapp.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
