# Generated by Django 3.2.15 on 2022-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0086_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
