# Generated by Django 3.2.15 on 2022-09-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0088_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
