# Generated by Django 3.2.15 on 2022-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0090_auto_20220913_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='shop_address',
            field=models.TextField(max_length=400),
        ),
    ]
