# Generated by Django 3.2.15 on 2022-09-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0091_alter_pharmacist_shop_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop_name',
            new_name='Pharmacist',
        ),
    ]
