# Generated by Django 3.2.15 on 2022-09-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0095_inventory_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
