# Generated by Django 3.2.15 on 2022-09-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0096_alter_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='status',
        ),
    ]
