# Generated by Django 3.2.15 on 2022-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0099_auto_20220914_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
