# Generated by Django 3.2.15 on 2022-10-08 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0101_auto_20220920_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='city',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='contact_no',
            field=models.CharField(default='0', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='aadhaarno',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='contactno',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='full_name',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='latitude',
            field=models.CharField(default='0', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='longitude',
            field=models.CharField(default='0', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='datashare',
            name='aadhaarno',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='datashare',
            name='contactno',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AlterField(
            model_name='datashare',
            name='full_name',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='docdatashare',
            name='aadhaarno',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='docdatashare',
            name='contactno',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AlterField(
            model_name='docdatashare',
            name='full_name',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contactno',
            field=models.CharField(default='0', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhaarno',
            field=models.CharField(default='0', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='contact_no',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_no',
            field=models.CharField(default='0', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='aadhaarno',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contactno',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='contact_no',
            field=models.CharField(default='0', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pincode',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
