# Generated by Django 3.2.15 on 2022-10-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0102_auto_20221008_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
