# Generated by Django 3.2.15 on 2022-10-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0103_auto_20221008_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='videocall',
            field=models.BooleanField(default=False),
        ),
    ]
