# Generated by Django 3.2.15 on 2022-10-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0104_user_videocall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
