# Generated by Django 3.2.15 on 2022-11-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0105_auto_20221020_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ambulncedatashare',
            name='time',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='datashare',
            name='time',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='docdatashare',
            name='time',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.CharField(default='0', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
