# Generated by Django 3.2.15 on 2022-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0106_auto_20221106_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdatashare',
            name='prescription',
            field=models.TextField(null=True),
        ),
    ]
