# Generated by Django 3.2.15 on 2022-12-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0107_docdatashare_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdatashare',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
