# Generated by Django 3.2.15 on 2022-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0108_alter_docdatashare_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulncedatashare',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='datashare',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
