# Generated by Django 3.2.15 on 2022-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0111_docdatashare_rtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='email_pharm',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
