# Generated by Django 4.1.4 on 2022-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cncapp", "0113_auto_20221223_1613"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pathologydatashare",
            old_name="Doctor",
            new_name="pathologist",
        ),
        migrations.AddField(
            model_name="pathologydatashare",
            name="rtc",
            field=models.TextField(null=True),
        ),
    ]
