# Generated by Django 3.2.16 on 2023-01-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0114_rename_doctor_pathologydatashare_pathologist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docdatashare',
            old_name='time',
            new_name='timeofshare',
        ),
    ]
