# Generated by Django 3.2.16 on 2023-01-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0116_docdatashare_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
