# Generated by Django 3.2.16 on 2023-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0120_tempory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempory',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
