# Generated by Django 3.2.16 on 2023-01-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0123_auto_20230117_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docdatashare',
            old_name='channel',
            new_name='channelname',
        ),
    ]
