# Generated by Django 3.2.16 on 2023-01-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0125_rename_channelname_docdatashare_channelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashare',
            name='date',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
