# Generated by Django 3.2.16 on 2023-01-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0126_datashare_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologydatashare',
            name='channelName',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='pathologydatashare',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pathologydatashare',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathologydatashare',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
