# Generated by Django 3.2.16 on 2023-01-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0127_auto_20230118_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashare',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
