# Generated by Django 3.2.16 on 2023-01-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0128_datashare_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
