# Generated by Django 3.2.16 on 2023-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncapp', '0129_remove_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='docdatashare',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
